services:
  - type: web
    name: virtualmall
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://ljauoakreigqqhmpjlh.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
